// modelsrv-otel-exporter is a minimal OpenTelemetry Collector distribution that
// includes the httpcheck receiver and the EmELand exporter. It probes HTTPS
// endpoints for TLS certificate expiry and maps the results into EmELand
// Findings, exposed via the standard modelsrv HTTP API.
//
// A complete config can be generated by modelsrv's certprobe subcommand:
//
//	modelsrv certprobe --otel-config-out collector.yaml --server http://modelsrv:8080/api/
package main

import (
	"fmt"
	"os"

	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver"
	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/otelcol"

	"emeland.io/modelsrv-otel-exporter/internal/emelandexporter"
)

func main() {
	info := component.BuildInfo{
		Command:     "modelsrv-otel-exporter",
		Description: "OTel Collector with httpcheck receiver and EmELand exporter",
		Version:     "0.1.0",
	}

	settings := otelcol.CollectorSettings{
		BuildInfo: info,
		Factories: components,
	}

	cmd := otelcol.NewCommand(settings)
	if err := cmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func components() (otelcol.Factories, error) {
	var factories otelcol.Factories
	var err error

	factories.Receivers, err = otelcol.MakeFactoryMap(httpcheckreceiver.NewFactory())
	if err != nil {
		return otelcol.Factories{}, fmt.Errorf("build receiver factories: %w", err)
	}

	factories.Exporters, err = otelcol.MakeFactoryMap(emelandexporter.NewFactory())
	if err != nil {
		return otelcol.Factories{}, fmt.Errorf("build exporter factories: %w", err)
	}

	return factories, nil
}
